version: "3.7"

services:
  database:
    container_name: test_database
    image: postgres:alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: training
    ports:
      - 5001:5432
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
